apiVersion: v1
kind: ConfigMap
metadata:
  name: stackelberg-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: stackelberg-scheduler
      plugins:
        preFilter:
          enabled:
          - name: StackelbergScheduler
        filter:
          enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
          - name: NodePorts
          - name: NodeUnschedulable
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeBinding
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
        score:
          enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodePreferAvoidPods
          - name: TaintToleration
          - name: ImageLocality
      pluginConfig:
      - name: StackelbergScheduler
        args:
          apiEndpoint: "http://localhost:5000"