apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    tenant: "Web-App"
  annotations:
    stackelberg.scheduler/budget: "150.0"
    stackelberg.scheduler/preferences: '{"cpu": 1.5, "memory": 1.0}'
spec:
  schedulerName: stackelberg-scheduler
  containers:
  - name: web-app
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi